### ISSUE TITLE
[BUG] Application closes unexpectedly after just opening it

### ISSUE THREAD

**Issue by xTrimy** [floh22/LeagueBroadcastHub#175]
The application closes unexpectedly after just opening it.

### Log:
[14-36-12] [WARNING] Could not download https://cdn.communitydragon.org/latest/champion/Nilah/splash-art/centered
The remote server returned an error: (404) Not Found.
[14-36-12] Outdated Offsets detected. Downloading new ones
[14-36-12] Fetching new offsets from https://raw.githubusercontent.com/floh22/LeagueBroadcast/v2/Offsets/Offsets-12.13.1.json
[14-36-12] [WARNING] Could not download https://raw.githubusercontent.com/floh22/LeagueBroadcast/v2/Offsets/Offsets-12.13.1.json: The remote server returned an error: (404) Not Found.
[14-36-12] Received updated offsets
[14-36-12] New Offsets not yet online. Checking to make sure if new patch should already be used
[14-36-12] [WARNING] App Crash detected. Writing Crash report to CrashLogs\Crash-2022-07-16-14-36.log

### Crash Report:
--- LeagueBroadcast Crash Report --- 
Looks like Viego and Morde bugs got the better of us.

Time: 2022.07.16-14:36
Description: One or more errors occurred. (Object reference not set to an instance of an object.)

Stacktrace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateGameVersion(FarsightConfig oldVersion) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 97
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateValues(String readValues) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 116
   at LeagueBroadcast.Common.Data.Config.JSONConfigProvider.ReadConfig(JSONConfig config) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Config\JSONConfigProvider.cs:line 66
   at LeagueBroadcast.Common.Controllers.ConfigController.LoadOffsetConfig() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 78
   at LeagueBroadcast.Common.Controllers.AppStateController.LoadOffsets() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 251
   at LeagueBroadcast.Common.Controllers.AppStateController.ConnectToClient() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 148
   at LeagueBroadcast.Common.Controllers.AppStateController.InitConnection() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 108
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

-- System Details -- 
League Broadcast Version: 1.4.106.21326
OS: Win 10 2009

**Comment by dawxyz** [comment]
its because the offsets arent updated to the latest patch i think

**Comment by xTrimy** [comment]
@dawxyz Yes, I thought of that too after reading the logs. I'll keep the issue open to notify @floh22 about that.

**Comment by MDvorky** [comment]
Isn't there a way to update it automatically or make it more automatic?

**Comment by xTrimy** [comment]
@MDvorky I've updated the offsets here: https://github.com/xTrimy/LeagueBroadcast ... Add this repository to the configs and it should work. I tested it after updating and it works, not sure if all works fine though, tell me if you found any issue, it's my first time to test some offsets :D 

Thanks go to @floh22 for sending me the instructions on how to update the offsets.
