### ISSUE TITLE
[BUG] Crushing on Launch 

### ISSUE THREAD

**Issue by jonhdead3** [floh22/LeagueBroadcastHub#247]
Is it because of the new patch that the application crashing ?
2 days ago was "working". Any help will be appreciated.
Best regards!

**Comment by Bouillot-Rngk** [comment]
I also have issues opening League Broadcast. Worked perfectly yesterday for a stream, but with the new patch, it crashes right after the update, on the main menu. 
Here is the crash log : 
[Crash-2023-04-05-16-46.log](https://github.com/floh22/LeagueBroadcast/files/11160140/Crash-2023-04-05-16-46.log)

**Comment by jubeal** [comment]
It seems that the Farsight.json is not generated at the lauch of the app. I guess that's the source of the issue but I am not sure.
Here is my crashlog for this issue:
```
--- LeagueBroadcast Crash Report --- 
Still more stable than the League Client

Time: 2023.04.05-19:39
Description: One or more errors occurred. (Value cannot be null. (Parameter 'a'))

Stacktrace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateGameVersion(FarsightConfig oldVersion) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 209
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateValues(String readValues) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 233
   at LeagueBroadcast.Common.Data.Config.JSONConfigProvider.ReadConfig(JSONConfig config) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Config\JSONConfigProvider.cs:line 64
   at LeagueBroadcast.Common.Controllers.ConfigController.LoadOffsetConfig() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 78
   at LeagueBroadcast.Common.Controllers.AppStateController.LoadOffsets() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 254
   at LeagueBroadcast.Common.Controllers.AppStateController.ConnectToClient() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 147
   at LeagueBroadcast.Common.Controllers.AppStateController.InitConnection() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.6.50.0
OS: Win 10 2009
```

**Comment by jonhdead3** [comment]
Same problem I gues. Any fixes so far ?

--- LeagueBroadcast Crash Report --- 
Still more stable than the League Client

Time: 2023.04.05-19:48
Description: One or more errors occurred. (Value cannot be null. (Parameter 'a'))

Stacktrace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateGameVersion(FarsightConfig oldVersion) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 209
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateValues(String readValues) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 233
   at LeagueBroadcast.Common.Data.Config.JSONConfigProvider.ReadConfig(JSONConfig config) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Config\JSONConfigProvider.cs:line 64
   at LeagueBroadcast.Common.Controllers.ConfigController.LoadOffsetConfig() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 78
   at LeagueBroadcast.Common.Controllers.AppStateController.LoadOffsets() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 254
   at LeagueBroadcast.Common.Controllers.AppStateController.ConnectToClient() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 147
   at LeagueBroadcast.Common.Controllers.AppStateController.InitConnection() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.6.50.0
OS: Win 10 2009

**Comment by jubeal** [comment]
Ok found it. The offsets must be updated at every patchs by hand, and we have to wait for @floh22 to update the offsets folder because it is needed to work with the 13.7 patch of league of legends.

So now we have to wait ^^ I hope our gardian angel will be able to take care of that soon.

**Comment by C1sterna** [comment]
check this https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight

**Comment by DjArix** [comment]
Same problem, Here is my crashlog:

--- LeagueBroadcast Crash Report --- 
Still more stable than the League Client

Time: 2023.04.07-18:10
Description: One or more errors occurred. (Value cannot be null. (Parameter 'a'))

Stacktrace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateGameVersion(FarsightConfig oldVersion) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 209
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateValues(String readValues) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 233
   at LeagueBroadcast.Common.Data.Config.JSONConfigProvider.ReadConfig(JSONConfig config) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Config\JSONConfigProvider.cs:line 64
   at LeagueBroadcast.Common.Controllers.ConfigController.LoadOffsetConfig() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 78
   at LeagueBroadcast.Common.Controllers.AppStateController.LoadOffsets() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 254
   at LeagueBroadcast.Common.Controllers.AppStateController.ConnectToClient() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 147
   at LeagueBroadcast.Common.Controllers.AppStateController.InitConnection() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.6.50.0
OS: Win 10 2009

**Comment by Honzalis** [comment]
Weird. Upon league start and spectate it worked fine for about 3 minutes (exc. the "could not load all champion data from the memory" error). Then it crashed, with same errors in the sent logs but won't load anymore. I hope this would get resolved quickly, since we heavily rely on the program to diferentiate from our competitors in our region.

**Comment by DjArix** [comment]
something that helped me was to download the previous version, replace files and re-download the latest version to update. // algo que me ayudo, fue bajar la versión anterior, reemplazar archivos y volver a descargar la última versión para que actualizara.

**Comment by jonhdead3** [comment]
So did it worked for you this way because I am still waiting. I haven't found anything helpful!

**Comment by DjArix** [comment]
Yes, but the solution didn't last long, it's already crashing again

**Comment by DjArix** [comment]
I was doing tests, while the league of legends client is closed, the program runs perfectly, but when opening the client and connecting with it, it crashes

**Comment by Hexasiel** [comment]
I updated the Offsets by Hand. Got rid of the crashes that way, but it's still not really working. I'm guessing thats due Leagues moving away from x86 support. 

To stop the program from crashing: 
- In Component.json inside the Config folder, set CheckForOffsets and CheckForUpdates to false 
- Edit (Or create if its not already there) the Fasight.json in the same folder. Use the code provided below.

As I said, this will not Fix the Programm, but someone might be able to work on it... I'll give an update if I manage to find a solution.

Fasight.json:
```
{
  "OffsetVersion": "13.7.1",
  "GameOffsets": {
    "Manager": "0x20d5978",
    "MapCount": "0x48",
    "MapRoot": "0x40",
    "MapNodeNetId": "0x20",
    "MapNodeObject": "0x28"
  },
  "ObjectOffsets": {
    "ID": "0x10",
    "NetworkID": "0xc8",
    "Team": "0x3c",
    "DisplayName": "0x60",
    "DisplayNameLength": "0x70",
    "Pos": "0x220",
    "Mana": "0x340",
    "MaxMana": "0x358",
    "Health": "0x1058",
    "MaxHealth": "0x1070",
    "CurrentGold": "0x2118",
    "GoldTotal": "0x2130",
    "EXP": "0x4018",
    "Name": "0x38a0"
  },
  "FileVersion": "1.0"
}
```

(Edit: Updated the Offsets since they were outdated)

**Comment by DjArix** [comment]
ahí probe la configuración indicada @Hexasiel y de momento parece funcionar, muchas gracias! // There I tried the indicated configuration @Hexasiel and for now it seems to work, thank you very much!

**Comment by Hexasiel** [comment]
I managed to fix the code to get it to work with the new x64 version of the game. The latest changes by @floh22 are doing the same thing, I just wasn't expecting an update anymore at this point. 

**However**, there is still a problem that causes the broadcasted to fail and I have no Idea what id causing this.
![Bild_2023-04-17_095713077](https://user-images.githubusercontent.com/65324515/232421701-f79a8f6d-cf5c-4f18-93e6-701980e41842.png)

(edit: spelling.)

**Comment by DjArix** [comment]
ya descargue la actualizacion, el programa corre a la perfeccion, pero al momento de estar en el modo espctador o en la replay, el programa se cierra solo :/ // I already downloaded the update, the program runs perfectly, but at the moment of being in the spectator mode or in the replay, the program closes itself :/

**Comment by Honzalis** [comment]
While i was in replay  the program ran fine, but when spectating a running game, it crashed. Here are the logs
[Crash-2023-04-19-02-14.log](https://github.com/floh22/LeagueBroadcast/files/11267306/Crash-2023-04-19-02-14.log)
[Log-2023-04-19-02-12.log](https://github.com/floh22/LeagueBroadcast/files/11267309/Log-2023-04-19-02-12.log)

**Comment by floh22** [comment]
Should be fixed in latest release. Reopen if the problem persists
