### ISSUE TITLE
Could not read all champion data from memory error

### ISSUE THREAD

**Issue by jonhdead3** [floh22/LeagueBroadcastHub#250]
I am getting this error it seems that the application works fine but after a bit it crushes and some animation doesn't work properly. 
![image_2023-04-17_120456289](https://user-images.githubusercontent.com/129967662/232453405-ac0cf998-68c9-45fe-b88d-db9be5292201.png)

**Comment by jonhdead3** [comment]
My crush log is this
--- LeagueBroadcast Crash Report --- 
Gotta fix this somehow... Up Up Down Down Left Right Left Right B A Enter... Nah, still broken

Time: 2023.04.17-11:01
Description: The given key 'Turret_T1_R_03_A' was not present in the dictionary.

Stacktrace: 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LeagueBroadcast.Ingame.Data.Provider.LiveEventsDataProvider.OnDamageDealt(LiveEvent e) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Provider\LiveEventsDataProvider.cs:line 267
   at LeagueBroadcast.Ingame.Data.Provider.LiveEventsDataProvider.ReceiveLiveEvent(Object sender, LiveEvent e) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Provider\LiveEventsDataProvider.cs:line 233
   at LeagueBroadcast.Trinket.LiveEventConnector.<Connect>b__9_0() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast.Trinket\LiveEventConnector.cs:line 87
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.6.50.0
OS: Win 10 2009

**Comment by ALUMNOAT** [comment]
I got kinda the same error

crashlog: [https://pastie.io/tqiooi.tex](https://pastie.io/tqiooi.tex)
log: [https://pastie.io/rokhin.cs](https://pastie.io/rokhin.cs)
It was a "spectate game"

**Comment by shinilee** [comment]
same here getting error

**Comment by SixiNeri** [comment]
Same here, error ingame

**Comment by FireFoXz09** [comment]
New version is out. Maybe it was caused from a memory problem. Try it and keep us updated.

**Comment by FKLevi1** [comment]
Hello, I am having the same error message. How did you guys fix it??

![image](https://github.com/floh22/LeagueBroadcast/assets/96711047/941f1887-ab3a-4c9a-a952-5d90dc306198)
