### ISSUE TITLE
[BUG] - App dont run after add directory of my game. 

### ISSUE THREAD

**Issue by roobdesigns** [floh22/LeagueBroadcastHub#253]
Starting APP the first problem
http://postimg.cc/ts8K88RN

I fix LeagueBroadcast-1.7.1\Config\Component

{
  "DataDragon": {
    "MinimumGoldCost": 2000,
    "Region": "global",
    "Locale": "en_US",
    "CDN": "https://ddragon.leagueoflegends.com/cdn",
    "CDragonRaw": "https://raw.communitydragon.org",
    "Patch": "latest"
  },
  "PickBan": {
    "IsActive": true,
    "UseDelay": false,
    "DelayValue": 300,
    "DefaultBlueColor": "rgb(66, 133, 244)",
    "DefaultRedColor": "rgb(234, 67, 53)"
  },
  "Ingame": {
    "IsActive": true,
    "UseLiveEvents": true,
    "DoLevelUp": true,
    "DoItemCompleted": true,
    "SeriesGameCount": 3,
    "Objectives": {
      "DoBaronKill": true,
      "DoDragonKill": true,
      "DoInhibitors": false,
      "DoObjectiveSpawnPopUp": false,
      "DoObjectiveKillPopUp": false,
      "UseCustomDragonTimer": true,
      "UseCustomBaronTimer": false
    },
    "Teams": {
      "DoTeamNames": false,
      "DoTeamIcons": false,
      "DoTeamScores": false
    },
    "UseCustomScoreboard": false
  },
  "Replay": {
    "IsActive": true,
    "UseAutoInitUI": true
  },
  "PostGame": {
    "IsActive": false
  },
  "App": {
    "LogLevel": 2,
    "CheckForUpdates": true,
    "UpdateRepositoryUrl": "https://github.com/floh22/LeagueBroadcast",
    "UpdateRepositoryName": "floh22/LeagueBroadcast",
    "LeagueInstall": [
      "C:\\",
      "D:\\",
      "E:\PLAY HARD\GAMES\Riot Games\League of Legends",
      "F:\\",
      "C:\\Program Files",
      "C:\\Program Files (x86)"
    ],
    "CheckForOffsets": true,
    "OffsetRepository": "https://api.github.com/repos/floh22/LeagueBroadcast/contents/Offsets?ref=v2",
    "OffsetPrefix": "Offsets-"
  },
  "FileVersion": "1.5"
}

And try start app again, but dont run.

**Comment by FFFFFFFXXXXXXX** [comment]
The offsets for the current path were just added, please try again if it works now

**Comment by roobdesigns** [comment]
The problem persist

--- LeagueBroadcast Crash Report --- 
Everything went according to plan. Seriously, this is the best case scenario.

Time: 2023.04.21-10:10
Description: Bad JSON escape sequence: \P. Path 'App.LeagueInstall[1]', line 54, position 11.

Stacktrace: 
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at LeagueBroadcast.Common.Data.Config.JSONConfigProvider.ReadConfig(JSONConfig config) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Config\JSONConfigProvider.cs:line 54
   at LeagueBroadcast.Common.Controllers.ConfigController..ctor() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 40
   at LeagueBroadcast.Common.Controllers.ConfigController.GetInstance() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 97
   at LeagueBroadcast.Common.Controllers.ConfigController.get_Instance() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 17
   at LeagueBroadcast.Common.Controllers.BroadcastController.EarlyInit() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\BroadcastController.cs:line 85
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at LeagueBroadcast.App.Main()

-- System Details -- 
League Broadcast Version: 1.7.1.0
OS: Win 10 2009

**Comment by FFFFFFFXXXXXXX** [comment]
Im not exactly sure what happened to your config file, but the correct paths are:

```json
"LeagueInstall": [
    "C:\\",
    "D:\\",
    "E:\\PLAY HARD\\GAMES\\Riot Games\\League of Legends",
    "F:\\",
    "C:\\Program Files",
    "C:\\Program Files (x86)"
]
```

hopefully that works :)
