### ISSUE TITLE
[BUG] The program shuts down when I run spectate

### ISSUE THREAD

**Issue by sod101316** [floh22/LeagueBroadcastHub#256]
--- LeagueBroadcast Crash Report --- 
Everything went according to plan. Seriously, this is the best case scenario.

Time: 2023.05.05-17:36
Description: Error getting value from 'blueGold' on 'LeagueBroadcast.Ingame.State.StateData'.

Stacktrace: 
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)
   at LeagueBroadcast.Http.WSServer.SendEventToAllAsync(LeagueEvent leagueEvent) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Http\WSServer.cs:line 90
   at LeagueBroadcast.Common.Controllers.IngameController.DoTick() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\IngameController.cs:line 261
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.7.1.0
OS: Win 10 2009

When I run a spectator, the program shuts down and these log files remain. Is there a solution?

**Comment by loverlsp** [comment]
x2

**Comment by Erusedo** [comment]
I have the same issue here

**Comment by Myllot** [comment]
Same here.

**Comment by syuanlyu** [comment]
Same here.

**Comment by nonenim** [comment]
Same here.

**Comment by sdomi4** [comment]
Is this still occuring? Or was it related to offsets at the time?

**Comment by syuanlyu** [comment]
It's fine now.
It related to offsets.

Dominik ***@***.***> 於 2023年7月26日 週三 下午3:20寫道：
