### ISSUE TITLE
[BUG] Language change doesn't allow LB to reopen anymore

### ISSUE THREAD

**Issue by JoanJuan10** [floh22/LeagueBroadcastHub#295]
**Describe the bug**
Whenever changing the language of League Broadcast and then restarting (Example is with Spanish Language), makes the app to crash.

**To Reproduce**
1. Fresh install on LB
2. Go to Settings and change language to Spanish
3. Restart

**Expected behavior**
A fast restart to make items display in spanish.

**Material**
Logs:
```
--- LeagueBroadcast Crash Report --- 
Everything went according to plan. Seriously, this is the best case scenario.

Time: 2023.10.06-10:18
Description: Value cannot be null. (Parameter 'source')

Stacktrace: 
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at LeagueBroadcast.Common.Data.Provider.DataDragon.Init() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Provider\DataDragon.cs:line 207
   at LeagueBroadcast.Common.Data.Provider.DataDragon.<>c.<<-ctor>b__21_0>d.MoveNext() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Provider\DataDragon.cs:line 125
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.7.22.0
OS: Win 10 2009
```

**Additional context**
Changing the language back to en_US in the component.json makes the app work again and open normally.

**Comment by overkido** [comment]
only works in English

**Comment by JoanJuan10** [comment]
Agreed. Why even have a language selector if it only works the default one?

**Comment by alfonsomartinde** [comment]
Same issue here. How can I fix that? Thanks!
