### ISSUE TITLE
[BUG] Application is crashing even with the new offsets. See error message.

### ISSUE THREAD

**Issue by neeemo** [floh22/LeagueBroadcastHub#300]
Getting a crash with the latest patch 13.21, even with the new offsets

--- LeagueBroadcast Crash Report --- 
Looks like Viego and Morde bugs got the better of us.

Time: 2023.10.27-23:31
Description: The given key 'Turret_T2_R_03_A' was not present in the dictionary.

Stacktrace: 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LeagueBroadcast.Ingame.Data.Provider.LiveEventsDataProvider.OnDamageDealt(LiveEvent e) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Provider\LiveEventsDataProvider.cs:line 280
   at LeagueBroadcast.Ingame.Data.Provider.LiveEventsDataProvider.ReceiveLiveEvent(Object sender, LiveEvent e) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Provider\LiveEventsDataProvider.cs:line 244
   at LeagueBroadcast.Trinket.LiveEventConnector.<Connect>b__9_0() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast.Trinket\LiveEventConnector.cs:line 87
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

-- System Details -- 
League Broadcast Version: 1.7.22.0
OS: Win 10 2009

**Comment by neeemo** [comment]
Can't seem to get the new offsets for 13.21 to work. Anyone else got it working? Thanks!

**Comment by sdomi4** [comment]
Same as #301, closing duplicate here
