### ISSUE TITLE
[BUG] The given key 'Turret_[...]' was not present in the dictionary

### ISSUE THREAD

**Issue by frafticekcz** [floh22/LeagueBroadcastHub#301]
--- LeagueBroadcast Crash Report --- 
Still more stable than the League Client

Time: 2023.10.28-19:07
Description: The given key 'Turret_T2_L_03_A' was not present in the dictionary.

Stacktrace: 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LeagueBroadcast.Ingame.Data.Provider.LiveEventsDataProvider.OnDamageDealt(LiveEvent e) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Provider\LiveEventsDataProvider.cs:line 267
   at LeagueBroadcast.Ingame.Data.Provider.LiveEventsDataProvider.ReceiveLiveEvent(Object sender, LiveEvent e) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Provider\LiveEventsDataProvider.cs:line 233
   at LeagueBroadcast.Trinket.LiveEventConnector.<Connect>b__9_0() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast.Trinket\LiveEventConnector.cs:line 87
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.7.22.0
OS: Win 10 2009

**Comment by sdomi4** [comment]
Seems to be related to turret plates; happens with different keys, presumably all turrets are affected:
- `Turret_T2_C_05_A`
- `Turret_T2_L_03_A`
- `Turret_T1_R_03_A`

**Comment by sdomi4** [comment]
Correction, it's actually related to the OnDamageGiven Event ([here](https://github.com/floh22/LeagueBroadcast/blob/c76e8f82cbe125720b8aa70cedf251dcb8da34fe/LeagueBroadcast/Ingame/Data/Provider/LiveEventsDataProvider.cs#L264)); removing it from LiveEvents.ini *should* fix this; although there have been some reports that it still occurs afterwards.

@frafticekcz do you have `OnDamageGiven` in your `LiveEvents.ini` (located in the Config folder in your League folder)? If yes, does removing the line fix the issue?

**Comment by neeemo** [comment]
I removed ondamagegiven in the liveevents-ini and i still got a crash, even with the new offsets that you added 2 hours ago. Seems to be somewhat solved though, restarting the app with replay on seems to be working now.

Will report back if it further crashes during tonights tournament casts.
