### ISSUE TITLE
Crashing on 14.2

### ISSUE THREAD

**Issue by Xahrie** [floh22/LeagueBroadcastHub#316]
The system is crashing on patch 14.2. The farsight.json might not be up to date.

--- LeagueBroadcast Crash Report --- 
Still more stable than the League Client

Time: 2024.01.25-17:41
Description: At least one object must implement IComparable.

Stacktrace: 
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, IComparer`1 comparer)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at LeagueBroadcast.Common.Data.Provider.DataDragon.GetLatestLocalPatch() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Provider\DataDragon.cs:line 194
   at LeagueBroadcast.Common.Data.Provider.DataDragon.GetLatestGameVersion() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Provider\DataDragon.cs:line 181
   at LeagueBroadcast.Common.Data.Provider.DataDragon.<>c.<<-ctor>b__21_0>d.MoveNext() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Provider\DataDragon.cs:line 124
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.7.22.0
OS: Win 10 2009

**Comment by Buta13** [comment]
Might be related to offsets that are not yet updated to 14.02
Software is stable by itself, but as soon as champselect starts (spec mode & solo training mode) or spectator mode loads, a similar crash happens [see below]

--- LeagueBroadcast Crash Report --- 
Gotta fix this somehow... Up Up Down Down Left Right Left Right B A Enter... Nah, still broken

Time: 2024.01.26-17:36
Description: One or more errors occurred. (Value cannot be null. (Parameter 'a'))

Stacktrace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task 1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task 1.get_Result()
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateGameVersion(FarsightConfig oldVersion) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 209
   at LeagueBroadcast.Ingame.Data.Config.FarsightConfig.UpdateValues(String readValues) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Ingame\Data\Config\FarsightConfig.cs:line 233
   at LeagueBroadcast.Common.Data.Config.JSONConfigProvider.ReadConfig(JSONConfig config) in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Data\Config\JSONConfigProvider.cs:line 63
   at LeagueBroadcast.Common.Controllers.ConfigController.LoadOffsetConfig() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\ConfigController.cs:line 64
   at LeagueBroadcast.Common.Controllers.AppStateController.LoadOffsets() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 254
   at LeagueBroadcast.Common.Controllers.AppStateController.ConnectToClient() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 147
   at LeagueBroadcast.Common.Controllers.AppStateController.InitConnection() in F:\Repos\LeagueOfLegends\LeagueBroadcast2\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

-- System Details -- 
League Broadcast Version: 1.7.22.0
OS: Win 10 2009`

**Comment by neeemo** [comment]
Was hoping for new offsets for this evening stream. No ETA? :)

Maybe if you release a guide/video or something for how you create the offsets step by step. Members here can help you when the patch comes? Cause I believe there are a lot of us, waiting for it every patch. Cause it is such a good free overlay that you have created.
