### ISSUE TITLE
[BUG] Crash after League startup

### ISSUE THREAD

**Issue by matthewpaolosbilo** [floh22/LeagueBroadcastHub#59]
**Describe the bug**
@floh22 Hello, League Broadcast is also crashing for me after opening League Client. I have a different error though.

**To Reproduce**

1. Launch LeagueBroadcast.exe
2. Launch League Client.
3. Login to League. (Crash happens here)

**Expected behavior**
App stays running after login.

**Crash Log**

```
--- LeagueBroadcast Crash Report --- 
Everything went according to plan. Seriously, this is the best case scenario.

Time: 2021.07.31-09:01
Description: Object reference not set to an instance of an object.

Stacktrace: 
   at LeagueBroadcast.Common.Controllers.AppStateController.GetLocalGameVersion(String rawPatch) in F:\Repos\LeagueOfLegends\LeagueBroadcast\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 240
   at LeagueBroadcast.Common.Controllers.AppStateController.ConnectToClient() in F:\Repos\LeagueOfLegends\LeagueBroadcast\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 138
   at LeagueBroadcast.Common.Controllers.AppStateController.InitConnection() in F:\Repos\LeagueOfLegends\LeagueBroadcast\LeagueBroadcast\Common\Controllers\AppStateController.cs:line 107
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

-- System Details -- 
League Broadcast Version: 1.4.65.21207
OS: Win 10 2009
```

**Additional context**

It's working great on my Intel CPU laptop, but this error occurs on my AMD CPU laptop.

**Comment by makermatic** [comment]
Having the same issue, especially during switch between draft and game

**Comment by FireFoXz09** [comment]
Similar thing here. The app crashes when the game start (after the champ select and the loading screen, at like 0:01 second in the game) Need to restart it each time

**Comment by DaBenjamins** [comment]
I am having the same issue.
